name: Daily bundle audit

on:
  schedule:
    - cron: "30 7 * * *"

jobs:
  bundle-audit-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Bundle audit
        run: bundle audit --update
